### ISSUE TITLE
Can't compile on Xcode 9/10

### ISSUE THREAD

**Issue by nu-steve** [crisp-im/crisp-sdk-ios#10]
When compiling a project with Crisp iOS SDK on Xcode 9 and 10, we get the following error. I think it would make sense to migrate the code to Swift 3.0+

![image](https://user-images.githubusercontent.com/11451910/45728857-7ee6ae80-bbfc-11e8-8dbe-dc150a8c9393.png)

**Comment by nu-steve** [comment]
The latest SDK with Xcode 10. Any ideas?

BR,
Steve - Whoolala CEO / Co-Founder

Mobile: (+86)18666223174
Email: steve@whoolala.com

**Comment by mywaystar** [comment]
I have been able to compile using a clean project.

Are you sure it’s Crisp?
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 19 Sep 2018, at 08:26, Steve <notifications@github.com> wrote:

The latest SDK with Xcode 10. Any ideas?

BR,
Steve - Whoolala CEO / Co-Founder

Mobile: (+86)18666223174
Email: steve@whoolala.com
