### ISSUE TITLE
Reference to class property '*' is not concurrency-safe because it involves shared mutable state; this is an error in the Swift 6 language mode

### ISSUE THREAD

**Issue by VAndrJ** [crisp-im/crisp-sdk-ios#101]
<img width="714" alt="Screenshot 2024-09-11 at 5 11 19 PM" src="https://github.com/user-attachments/assets/85351ac8-2e13-4ead-9580-52ac19b8eb62">
<img width="647" alt="Screenshot 2024-09-11 at 5 11 48 PM" src="https://github.com/user-attachments/assets/5ad771a8-c48a-49b9-9a60-67bc90e1822f">

**Comment by nesium** [comment]
This is fixed in [2.6.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.6.0). Feel free to reopen the ticket if you encounter any other related issue.
