### ISSUE TITLE
Emails with single character domains flag as mistyped despite being valid

### ISSUE THREAD

**Issue by john-numerade** [crisp-im/crisp-sdk-ios#107]
When using the test email `w16@n.com` the Crisp chat client prompts of a warning of a mistyped email despite the account containing a valid, possible URL. As a result of the warning I am unable to chat with the representative even though it is a real possible email.

Either the checker used within the SDK should allow all valid domains or else a user should still be able to chat with a representative even if their email address isn't correct/valid.

Reference information on single-letter second-level domains. https://en.wikipedia.org/wiki/Single-letter_second-level_domain

Screenshot attached of the message.

![simulator_screenshot_4C74C853-F145-43A8-8585-50A9B2DDAAEE](https://github.com/user-attachments/assets/ff060fcb-7bc8-431d-bc45-c9f69ce66dcd)

Tested with `crisp-sdk-ios` v. `2.5.1`.

**Comment by john-numerade** [comment]
Apparently this is a website/API issue and also was closed on my related Android SDK ticket.

Linking the other task for context and closing as well.

https://github.com/crisp-im/crisp-sdk-android/issues/200#issuecomment-2548808611

**Comment by baptistejamin** [comment]
This email is not valid and then shall not be accepted.
