### ISSUE TITLE
React Native module?

### ISSUE THREAD

**Issue by gianpaj** [crisp-im/crisp-sdk-ios#14]
https://teabreak.e-spres-oh.com/swift-in-react-native-the-ultimate-guide-part-2-ui-components-907767123d9e

🙏

**Comment by walterholohan** [comment]
Bump. Is it in the pipeline to release a React Native module that will bridge the iOS and Android SDKs. I have created a custom bridge but am struggling to get the Android bridge to work correctly. Happy to contribute my custom bridge if it will speed up the process.

**Comment by walterholohan** [comment]
@gianpaj @baptistejamin I created a native bridge for Crisp's iOS and Android SDK's. You can check it out here https://github.com/walterholohan/react-native-crisp-chat-sdk. I plan to add in the rest of the SDK API methods over the coming days. Android still has 1 outstanding issue which is outlined in more detail here (https://github.com/crisp-im/crisp-sdk-android/issues/26#issuecomment-620867233)
