### ISSUE TITLE
Can't set name and email

### ISSUE THREAD

**Issue by Sasan-Angel** [crisp-im/crisp-sdk-ios#15]
I set name and email through your API but it won't be set at the first time crispView is loaded
But when the user opens a crisp view for the second time it will be Set.
I didn't know where is the best place for setting these properties so I tried putting it in app delegate or my home view controller and event multiple places or calling it twice but the problem persists. and the only way to set these properties is opening a crisp view more than once.
What do you think should I do?

**Comment by baptistejamin** [comment]
Hello!

We now made a brand new SDK with those features
