### ISSUE TITLE
Native SDK is not in the master branch

### ISSUE THREAD

**Issue by trevinwisaksana** [crisp-im/crisp-sdk-ios#19]
I'm trying to install the native Crisp iOS SDK using Cocoapods but it keeps reverting to the old version. After looking around I realized that it is in a separate branch called 'native-sdk'. 

Is this not available for use yet? If it is available can you please merge it with the master branch? Otherwise we would have to install it manually and it would look out of place. 

Thanks!

**Comment by baptistejamin** [comment]
We just released the iOS SDK on the master branch.
