### ISSUE TITLE
@_hasMissingDesignatedInitializers

### ISSUE THREAD

**Issue by zafarnajmi1** [crisp-im/crisp-sdk-ios#21]
How to Resolve this issue..?

**Comment by baptistejamin** [comment]
Do you have any additional details ?

**Comment by pamgoudarzi** [comment]
Try upgrading to Xcode 11.6. Had this problem occur on 11.3, upgraded to 11.6 and it got solved.

**Comment by nesium** [comment]
Closing this in favor of #29. Let us know if this is still a problem in the latest version (1.0.6).
