### ISSUE TITLE
Podfile integration

### ISSUE THREAD

**Issue by LudoLibon** [crisp-im/crisp-sdk-ios#26]
I use Pod and can't migrate from Crisp 0.1.30 to crisp 1.0.3
Pod install --repo-update works and says that Crisp 1.0.3 is installed and I see the framework in my Project. 
But the "import Crisp" failed with No such module 'Crisp'

I cleaned my project and deleted derived data between 0.1.30 to 1.3.0 migration. 
My environement is : 
Pod : 1.8.4
Xcode : Version 11.7 (11E801a)
platform :ios, '11.0', 
swift version : 4.2

**Comment by nesium** [comment]
Hi @LudoLibon. You'll need at least Cocoapods version 1.9 where they introduced support for xcframeworks.

**Comment by LudoLibon** [comment]
> Hi @LudoLibon. You'll need at least Cocoapods version 1.9 where they introduced support for xcframeworks.

Thanks, that's work with 1.9.3 cocoapod version (I just need to clean and delete derived data)
