### ISSUE TITLE
1.0.5 missing from Cocoapods registery 

### ISSUE THREAD

**Issue by walterholohan** [crisp-im/crisp-sdk-ios#28]
Can you publish the latest version to Cocoapods https://cocoapods.org/pods/Crisp?

At the moment version 1.0.3 is the latest that is available for download

**Comment by baptistejamin** [comment]
Hello!

There is a known problem with the latest Cocopods version so we can’t update yet the 1.0.5. 

A merge request was submitted and it should be available soon.

**Comment by floriangbh** [comment]
Hello, maybe the https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0 is fixing your issue ?

**Comment by nesium** [comment]
Closing this, as we've just published version 1.0.6 to CocoaPods Trunk.
