### ISSUE TITLE
1.0.3 hasMissingDesignatedInitializers

### ISSUE THREAD

**Issue by DrashtiJaviya-Openxcell** [crisp-im/crisp-sdk-ios#29]
I use Pod and installed pod version crisp 1.0.3
I tried with Pod install --repo-update works and says that Crisp 1.0.3 is installed and I see the framework in my Project.
But the "import Crisp" failed with No such module 'Crisp' and I found an error like 

**{{path}}/DerivedData/CrispDemo1-gkfxoeytlqjtltcxsdnybdsbtika/Build/Products/Debug-iphonesimulator/Crisp.framework/Modules/Crisp.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:19:35: Unknown attribute '_hasMissingDesignatedInitializers'** 

I also tried with manual integration of the framework but I get the same error. I also tried downgrading pod and user but the same error getting.

I cleaned my project and deleted derived data between 0.1.30 to 1.3.0 migration.
My environement is :
Pod : 1.10.0
Xcode : Version 11.3 
platform :ios, '11.0',
swift version : 5

**Comment by DrashtiJaviya-Openxcell** [comment]
We are still waiting for the response on this so could you please help us by letting us know how can we resolve this issue as we can not move forward with further development progress until we resolve this issue. I will be very grateful If anyone can do also help out to solve.

**Comment by eliottvincent** [comment]
Hello there, we will release a new version of the iOS SDK in the coming days.

**Comment by DrashtiJaviya-Openxcell** [comment]
@eliottvincent  Thanks For the response. Once you guys update SDK Version Please let us know.

**Comment by nesium** [comment]
We've just release version 1.0.6 which hopefully addresses this issue. Could you please try again with that version and let us know if you're still encountering the problem?

**Comment by DrashtiJaviya-Openxcell** [comment]
Hello @nesium 

I am facing still the same issue in the latest version which is you mentioned above. Here I attached an error screenshot for your reference and also share my project configuration. I tried to install with pod and Cocoa pod version: 1.10.0 I am used.

![Screenshot 2020-11-19 at 10 21 00 AM](https://user-images.githubusercontent.com/46279724/99623681-9e82f700-2a52-11eb-9946-60f5b6534e16.png)
![Screenshot 2020-11-19 at 10 27 04 AM](https://user-images.githubusercontent.com/46279724/99623741-bf4b4c80-2a52-11eb-87bf-066261da6985.png)
![Screenshot 2020-11-19 at 10 28 43 AM](https://user-images.githubusercontent.com/46279724/99623770-d5f1a380-2a52-11eb-9990-46cb2f4f9f26.png)

**Comment by nesium** [comment]
Hi @DrashtiJaviya-Openxcell. Thanks for checking!
Apparently this problem can even happen between point releases of Swift. See [this thread](https://forums.swift.org/t/cant-use-framework-compiled-with-swift-5-2-in-swift-5-1-3-project/35248). Is there a chance that you can upgrade to the latest Xcode and Swift version?

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
