### ISSUE TITLE
Unable to open the chat window programatically after closing it, see Image

### ISSUE THREAD

**Issue by pravishanth** [crisp-im/crisp-sdk-ios#3]
Faced this issue when on Crisp example app, 
[CrispChatIssue.pdf](https://github.com/crisp-im/crisp-sdk-ios/files/1320688/CrispChatIssue.pdf)

**Comment by tib** [comment]
Had the same issue, you have to call close before opening again.

```
Crisp.chat.close()
Crisp.chat.open()
```
