### ISSUE TITLE
SocketIO conflict

### ISSUE THREAD

**Issue by xHunter** [crisp-im/crisp-sdk-ios#30]
My project uses SocketIO-Client-Swift (15.2.0) and I'm getting a ton of warnings about classes being implemented in both frameworks (my app and the Crisp SDK) and also some runtime crashes from my calls to those classes.

**Comment by baptistejamin** [comment]
Hello!

Do you still have the same issue with the last iOS SDK (1.0.12) ?

**Comment by xHunter** [comment]
@baptistejamin yes, the issue still happening with the latest version (1.0.12)

This a example of the conflicts: 
```
Class _TtC8SocketIO13SocketManager is implemented in both 
App.app/Frameworks/SocketIO.framework/SocketIO (0x118361e98) 
and App.app/Frameworks/Crisp.framework/Crisp (0x114de1ea0). 
One of the two will be used. Which one is undefined.

**Comment by pizerg** [comment]
Implementing #65 will probably solve this issue
