### ISSUE TITLE
IOS Version

### ISSUE THREAD

**Issue by ArchiReport** [crisp-im/crisp-sdk-ios#32]
What is the minimum version of IOS?
I cant submit with 12.0.
Thanks for your help
Julien
(I have no error with Pod install)

**Comment by ArchiReport** [comment]
<img width="584" alt="Capture d’écran 2020-11-20 à 13 22 31" src="https://user-images.githubusercontent.com/23122751/99799741-78815380-2b33-11eb-8080-f27c561c8125.png">

**Comment by nesium** [comment]
Hi Julien. That is puzzling. We're building the app with an iOS deployment target of 10.0. If you look at the binary with otool, you can see that the minimum version is 10.0…

```
$ otool -l ./Crisp.xcframework/ios-arm64_armv7/Crisp.framework/Crisp
…
Load command 9
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 10.0
      sdk 14.2
…
```

**Comment by nesium** [comment]
Hi Julien. I was able to upload a build with a iOS 12 deployment target to App Store Connect. Currently I have no idea what the problem could be. The `ITMS-90125` error looks suspicious as well. Do you have any idea where that is coming from?

**Comment by ArchiReport** [comment]
Thanks Marc,
I'll look.
I have compilation issues when using the code in Swift.
I had to redo everything in Objective-c.

**Comment by jcotteaux** [comment]
When i want to import Crisp in my Swift class, I have this error 

"Failed to build module 'Crisp' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced"

Do you have an idea ?

The 2 things may be related.

<img width="729" alt="Capture d’écran 2020-11-23 à 10 00 01" src="https://user-images.githubusercontent.com/7989536/99944137-ad2f1e00-2d72-11eb-8214-d2ca982676fe.png">

Thanks for your help

**Comment by jcotteaux** [comment]
With the same configuration, all is ok with 1.0.3 version

**Comment by nesium** [comment]
@jcotteaux What version of Xcode and Cocoapods are you using? Do you happen to run your build on an Apple Silicon machine?

**Comment by jcotteaux** [comment]
I archive my build on my Mac
- Cocoapods : 1.9.1
- XCode : 12.2

**Comment by nesium** [comment]
Thanks Julien! Could you please try again with Cocoapods version 1.10.0 as it contains changes related to XCFrameworks.

**Comment by jcotteaux** [comment]
TOP  @nesium !!
Everything seems to work.
Thank you for your help.
Have a nice day.
Julien

**Comment by ArchiReport** [comment]
👍
