### ISSUE TITLE
Our app build fails after installing Crisp chat on pod install

### ISSUE THREAD

**Issue by yakshaving** [crisp-im/crisp-sdk-ios#33]
Our app build fails after installing Crisp chat on pod install

Does this seem to happen for anyone else at all?

**Comment by Arthur-Guillaume** [comment]
Hi @yakshaving,

Had a build issue, fixed it by :
- Quit Xcode
- Update Cocoapods to version >= 1.10.0
- Delete `Pods/`
- Delete `~/Library/Developer/Xcode/DerivedData`
- pod install

Hope it can help.
