### ISSUE TITLE
Getting IRGen expression when Printing Out in Console

### ISSUE THREAD

**Issue by trevinwisaksana** [crisp-im/crisp-sdk-ios#34]
Example command: `po test`

Result:
```
error: virtual filesystem overlay file '/Users/mb/Library/Developer/Xcode/DerivedData/Crisp-aaaajuyrfyjaumgrrotvdtjcuvti/Build/Intermediates.noindex/ArchiveIntermediates/Crisp/IntermediateBuildFilesPath/Crisp.build/Release-iphonesimulator/Crisp.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

According to this [comment](https://bugs.swift.org/browse/SR-12783?focusedCommentId=56540&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-56540), your team needs to "compile their binary framework with `-no-serialize-debugging-options` if they are planning to distribute them to another machine."

I have made a [sample project ](https://drive.google.com/file/d/10hoUiXWKUb9QrC5tkYiXgP8VFKTUOpR5/view?usp=sharing)that just contains Crisp as a dependency. Please run `pod install` and set a breakpoint in the `viewDidLoad`. Run `po test` in the console and you should get the same error. I can confirm it is related to Crisp because when I removed it from Cocoapods, it can `po test` normally.

Note: I recommend to run on this on a machine that is not used to develop the Crisp framework as it should be missing the all-product-headers.yaml.

I am using Xcode 12.2, Cocoapods 1.10 and Crisp 1.0.6.

**Comment by trevinwisaksana** [comment]
Update: I've changed the permission settings for the sample project. You should be able to access it now.

**Comment by trevinwisaksana** [comment]
Any updates on this? Have you been able to replicate it?

**Comment by nesium** [comment]
Hi @trevinwisaksana. Thanks for the example project, the additional info and your patience!
I've just pushed a new version (1.0.7) which was built with the `-no-serialize-debugging-options` flag. Let us know if this solves your issue or in the case it still persists. Thanks!
