### ISSUE TITLE
Getting 'Missing field 'user_id' in class Participant' error when using after hours

### ISSUE THREAD

**Issue by tomerubin2** [crisp-im/crisp-sdk-ios#36]
When trying to use the chat when in after hours I get this error alert:
Missing field 'user_id' in class Participant

![image](https://user-images.githubusercontent.com/3989998/102519468-2e8c7e80-409b-11eb-8342-7a2559c202f3.jpeg)

Then when trying to using the 'help' link in the app again this message is displayed
![image](https://user-images.githubusercontent.com/3989998/102519531-4532d580-409b-11eb-97c1-155d3d6e015a.jpeg)

And still gets this message on every time they try to open the help link from the app

**Comment by valeriansaliou** [comment]
For @nesium for later. Looks like it's still occurring in the last release.

**Comment by nesium** [comment]
I've double-checked the current implementation and I don't think that this can still happen.

@tomerubin2 Could you please make sure that you're using the latest version of the Crisp SDK which is `1.0.6`.

If unsure, you can see the used version when starting your app in the debug console. We're printing a string there which looks like this:
```
Initialized Crisp Crisp SDK Version 1.0.6 (Build 93).
```

Let us know if you're already on 1.0.6. Thanks!
