### ISSUE TITLE
Could not create URL from string

### ISSUE THREAD

**Issue by abdulazizSi** [crisp-im/crisp-sdk-ios#37]
Hi, I'm trying to use the SDK on ios with swift, and I'm facing this error in the console:
[error] Could not create URL from string 'https://settings.crisp.chat/client/website//"MyWebsitID"/prelude/?2020-12-22-2-54 PM'. Please report this to https://github.com/crisp-im/crisp-sdk-ios/issues/new and quote this message there.

My iPhone: iPhone x
iOS version: 14.2
Language: en
Region: Turkey

Steps:
1- Install the SDK using CocoaPods, and run pod update, SDK current version now is: 1.0.6
2- Updated my Info.plist with the privacy required.
3- Setup the SDK configuration in the AppDelegate by calling CrispSDK.configure(websiteID: "MyWebsitID") in didFinishLaunchingWithOptions.
4- Present ChatViewController from a button like this: present(ChatViewController(), animated: true).

Result: 
1- ChatViewController get presented showing loading indicator with "Starting chat.." text
2- get error in the console: [error] Could not create URL from string 'https://settings.crisp.chat/client/website//"MyWebsitID"/prelude/?2020-12-22-2-54 PM'. Please report this to https://github.com/crisp-im/crisp-sdk-ios/issues/new and quote this message there.

I talked to the live support and ask them how to use the API like : CrispSDK.user.email and CrispSDK.user.nickname
thy told me the following:
I will ask our developers
User email and user nickname, Second line and third line 
and It doesn't matter where you add it.

What did I tried so far:
1- I did try to add userName email etc in the AppDelegate after I set the websiteID, but still same error
2- I did try to add userName email etc before calling present(ChatViewController(), animated: true), and still same error

**Comment by abdulazizSi** [comment]
Update
I did test the same code on the following simulators and it works just fine without error
iPhone 8 ios13.6, iPhone 8 ios14.2, iPhone 12, iPhone 11 pro max ios14.2

but still having the error on my real device iPhone x ios14.2

**Comment by nesium** [comment]
Hi @abdulazizSi. Just to be sure, are you initializing the Crisp SDK with `CrispSDK.configure(websiteID: "MyWebsitID")` or was this just an example? Are you using you're real website ID as described [here](https://github.com/crisp-im/crisp-sdk-ios#3-configure-the-crisp-ios-sdk)? Thanks!

**Comment by abdulazizSi** [comment]
@nesium 
I'm initializing the Crisp SDK in the AppDelegate
and using the real websiteID, "MyWebsitID" is just an example 

the wired thing that on the simulator works but on real device it dos not, tested on real iPhone 11 pro max too

**Comment by nesium** [comment]
Thanks @abdulazizSi. This is now fixed in `1.0.8`. I missed the `PM` in your initial message. The bug was only happening on devices that were not using 24 hour time (AM/PM) so that might explain why the behavior was differing between the simulator and the real device. Please let us know if your still experiencing this problem.

**Comment by abdulazizSi** [comment]
Thank you so much @nesium you are the best, I do confirm that the problem is fixed

**Comment by nesium** [comment]
Awesome. Thanks for confirming!
