### ISSUE TITLE
Reset session cause instability

### ISSUE THREAD

**Issue by philippeauriach** [crisp-im/crisp-sdk-ios#39]
Hi, I'm currently trying Crisp SDK in my iOS app. It seems to work fines except for the following flow (user logout from my app then login with another account, I would like to have a new conversation started). 

Maybe I'm not doing what's right.

I have the following flow : 

-> User log in (or is logged in and open the app)
-> User profile data is fetched from my server
-> CrispSDK is called to update the user info
```swift
CrispSDK.setTokenID(tokenID: "crisp_" + user.id)
CrispSDK.session.setString(user.id, forKey: "userId")
CrispSDK.user.email = user.email
CrispSDK.user.nickname = user.firstName + " " + user.lastName
```
-> User open a chat sdk, write a message
-> A conversation A is created in Crisp, with the correct user info presented

-> User logs out from my app and `CrispSDK.session.reset()` is called
-> User logs into another account
-> New user data is fetched from my server, and filled into CrispSDK (same code as in step 3)
-> New user open chat sdk
-> 🛑 KO: New User sees conversation A entered by the previous user
-> 🛑 KO: New User can write and send, and message appear in the conversation A created by the original user
-> 🛑 KO: In Crisp, the conversation A with the original user is updated with the data of the new user 

-> New user kill the app
-> New user relaunch the app
-> New user open chat sdk
-> ✅ Expected behaviour: Chat is blank, new conversation B is created in Crisp, with the new user data

Thanks

**Comment by nesium** [comment]
Hi @philippeauriach. This issue has been adressed in the 1.0.9 release. Let us know if this solves it for you. Thanks!

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!

**Comment by hanifsgy** [comment]
Hello @nesium,
This issue still persists in versions `2.8.0` and `2.6.0`. Previously, we used version `1.0.11`, which worked fine. After calling `CrispSDK.session.reset()`, any previous messages would disappear. Without making any changes or modifications, we only wanted to update the `Crisp SDK`, but the issue continues to persist.

**Comment by nesium** [comment]
@hanifsgy 

I've had another look at this. There's really not a lot happening in the `reset` call. We're saving the session ID in the `UserDefaults` and remove it when `reset` is called.

What I can think of why this might go wrong:
- Are you calling the method from a non-main thread?
- Do you quit the app immediately after the call (e.g. by calling `exit`)?
- Do you have background execution turned off (`UIApplicationExitsOnSuspend` in your app's plist) and your users immediately send the app into the background?
- Are you testing this only in the simulator and immediately quit the app after the `reset` call?

Which brings me to my next question: Does it happen reliably, i.e. all of the time or only some of the time?

If you're testing this in the simulator you can easily test this…

1. Open the app's Library folder in Finder (print `FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)` then open the path in Finder)
2. In the Preferences subfolder there's a file `im.crisp.chatbox.plist` which represents the SDK's UserDefaults. Before resetting there should be two keys `session` and `previous_session`.
3. If you call `reset`, after a short while (took a couple of seconds in my tests), `session` should be removed from the plist. Keep in mind to keep the app running in the simulator and not immediately quit it.

Does that work for you? Is `session` removed?

**Comment by hanifsgy** [comment]
Hello @nesium, sorry for the late response. I will answer your questions. I run tests on both physical devices and simulators.

- No, I'm calling on the main thread.
- I didn't quit immediately after the call.
- I didn't use `UIApplicationExitsOnSuspend`, which is deprecated in plist files.

Previously, I was using version `1.0.11`, and I did not encounter this bug; it always cleared within milliseconds, not seconds while keep my apps running -- after do logout session we immediately call ` CrispSDK.session.reset()`. 

I run tests on simulator to try inspecting the `im.crisp.chatbox.plist` file and noticed two keys: `session` and `previous_session`. I tried waiting for a few minutes and closing the app, but that didn't solve the issue. Upon inspecting the properties again, the `session` and `previous_session` still existed.

However, if I assign some random values like this:

```swift
CrispSDK.setTokenID(tokenID: UUID().uuidString)
```

It fetches a new chatbox instead, which solves my problem, but I don't think it's a good solution.

**Comment by nesium** [comment]
@hanifsgy Thanks for checking! I've now added `UserDefaults.synchronize` calls whenever `reset()` is called, which [shouldn't be needed](https://developer.apple.com/documentation/foundation/userdefaults/synchronize()) but appears to do the trick. 

The change is available in [2.9.0-beta.2](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.9.0-beta.2). Would be great if you could give this a try.

I have to check what the expected behavior is with regards to `setTokenID`.

**Comment by hanifsgy** [comment]
I’m testing [2.9.0-beta.2](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.9.0-beta.2) and the bug persists. I suspect it’s related to [https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/session-continuity/](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/session-continuity/). Should we reset `setTokenID` with `UUID V4`? Is there any change that makes Crisp `1.0.15` behave differently?

**Comment by nesium** [comment]
@hanifsgy I'm happy that you mentioned the `setTokenID` call. I took another look and there was indeed a bug where the Token ID was not reset when calling `CrispSDK.session.reset()`. I'm assuming this explains the behavior that you were seeing. A fix is available in [2.9.0-beta.3](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.9.0-beta.3). Maybe you can give it another try and see if this finally solves the issue for you.

**Comment by hanifsgy** [comment]
@nesium Nice! The bug does not occur in [2.9.0-beta.3](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.9.0-beta.3). Thank you for the quick response! 🙏🏻 We can close this issue while we wait for the SDK releases

**Comment by nesium** [comment]
Thanks for confirming @hanifsgy! Happy to hear that this is finally solved.

**Comment by nesium** [comment]
Hi @hanifsgy. I had to rollback the behavior in 2.9.0 to match the [behavior of the Web SDK](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/session-continuity/#how-to-associate-a-session-to-a-token). 

In order to make sure that the Token ID is reset you will need to set it to `nil` before calling `resetSession`. You can find the documentation [here](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/session/reset()).
