### ISSUE TITLE
Is it possible to set the language for the SDK?

### ISSUE THREAD

**Issue by walterholohan** [crisp-im/crisp-sdk-ios#42]
Hi,

I have a couple of queries on the React Native SDK asking if they can set the language of the SDK to something other than English. Is this possible? I might of missed something when configuring the iOS SDK for react native.

Open issue can be found here - https://github.com/walterholohan/react-native-crisp-chat-sdk/issues/21

**Comment by baptistejamin** [comment]
We've been testing this since yesterday.

The regular iOS SDK auto-detects the language and is using the device locale.

We are suspecting something with React-Native, that is not giving us the accurate device locale

**Comment by walterholohan** [comment]
Yeah I just thought the same. I dont think I set the locale in the info.plist file. Let me see if that fixes the issue.

**Comment by walterholohan** [comment]
Ok cool, thanks for investigating. I will take a look and see what I can do.

**Comment by iTarek** [comment]
> We've been testing this since yesterday.
> 
> The regular iOS SDK auto-detects the language and is using the device locale.
> 
> We are suspecting something with React-Native, that is not giving us the accurate device locale

My app is Arabic no matter what is the device local can we set the Crip SDK language or at least you get the language settings from the backend.

I tried 
` CrispSDK.locale = NSLocale(localeIdentifier: "ar") as Locale`

But it's not working, can you help pease

**Comment by baptistejamin** [comment]
Crisp is not **officialy** supporting Flutter, React Native, Cordova, Ionic, Xamarin, and what we call
"hybrid frameworks".


For those languages, you can either use the **un-official packages** (if there is one), or you can include Crisp in a webview, via the following method: [https://help.crisp.chat/en/article/how-can-i-embed-the-crisp-chatbox-in-an-external-link-bkfh98/](https://help.crisp.chat/en/article/how-can-i-embed-the-crisp-chatbox-in-an-external-link-bkfh98/)

**Comment by nesium** [comment]
It seems like the issue [was fixed](https://github.com/walterholohan/react-native-crisp-chat-sdk/issues/21#issuecomment-997459200) in the meantime.
