### ISSUE TITLE
"Search on Helpdesk" icon still shown even if disabled

### ISSUE THREAD

**Issue by andreikrx** [crisp-im/crisp-sdk-ios#43]
In the Crisp website settings you have "Show a link to helpdesk in the chatbox (if Crisp Helpdesk is configured)" setting. If you disable it, then the "search on helpdesk" icon in the top right of the chatbox window should disappear, along with the link from the first message of the chat. 
This works on the web chatbox, but not on the iOS SDK. On the iOS SDK, only the link in the first message of the chat is hidden, not the top right icon below the operators.

It's important to be able to hide it not only because of consistency but, if that icon appears, upon clicking, it shows a search bar and on the bottom a link "Open Helpdesk" which opens a browser window.  It is not desirable to exit the app like this.

Thank you

**Comment by nesium** [comment]
Hi @andreikrx. Thanks for your report. This has been addressed in the [latest version of the SDK](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.0.14). Feel free to reopen this issue if the issue persists.
