### ISSUE TITLE
EXC_BAD_ACCESS when using Crisp SDK

### ISSUE THREAD

**Issue by alokjha** [crisp-im/crisp-sdk-ios#46]
My iOS app is crashing when I try to use Crisp SDK in my project. It is happening inside Starscream pod which is used in my app and also used inside Crisp SDK. Tested with Crisp SDK version 1.0.13

Attaching screenshot
<img width="987" alt="Screenshot 2021-06-10 at 21 01 38" src="https://user-images.githubusercontent.com/5088746/121553963-631c3a00-ca2f-11eb-9055-f4199782fad2.png">.

Also I get run time warnings in logs when app starts due to same pod Starscream being used in both my app and Crisp SDK.
`objc[8734]: Class PodsDummy_Starscream is implemented in both /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Starscream.framework/Starscream (0x10988c728) and /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Crisp.framework/Crisp (0x105bd11f0). One of the two will be used. Which one is undefined.
objc[8734]: Class _TtC10Starscream12Decompressor is implemented in both /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Starscream.framework/Starscream (0x10988e4f8) and /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Crisp.framework/Crisp (0x105be03d0). One of the two will be used. Which one is undefined.
objc[8734]: Class _TtC10Starscream10Compressor is implemented in both /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Starscream.framework/Starscream (0x10988e620) and /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Crisp.framework/Crisp (0x105be04f8). One of the two will be used. Which one is undefined.
objc[8734]: Class _TtC10Starscream9WebSocket is implemented in both /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Starscream.framework/Starscream (0x10988df70) and /private/var/containers/Bundle/Application/F4E7AFDC-A9D2-45F3-B1C2-F976D762FD68/MyApp.app/Frameworks/Crisp.framework/Crisp (0x105bd13e8). One of the two will be used. Which one is undefined.`

**Comment by eliottvincent** [comment]
Can you please try with the latest version available? That is, version 1.0.14.

**Comment by alokjha** [comment]
@eliottvincent Getting same error with Crisp SDK version 1.0.15 too, both on Simulator as well as on device.

**Comment by pizerg** [comment]
Fixing #65 will probably solve this issue
