### ISSUE TITLE
Getting Errors When Chat Page Is Accessed between Android and iOS

### ISSUE THREAD

**Issue by kennethvl** [crisp-im/crisp-sdk-ios#47]
Info: I'm using iOS 14.6, in Xcode 12.5, and I'm using the SDK version 1.0.13 taken from Cocoapods.

So the product I'm integrating the Crisp chat is available on both iOS and Android.

In the Android version, the other developers already used the nickname with format "[name] ([role] / [userID])". But in the iOS version, I set it as "[name]" only, because the "role" and "userID" will be put as the visitor data.

However, I forgot that in our product, the user name is optional, thus in iOS it'll automatically sent as an empty string.

Then, I changed the implementation to avoid the nickname to be set as empty string from the iOS version. However, every time I opened ChatViewController(), it keeps showing the "Error starting chat" alert. Like the picture below.

![IMG_7254](https://user-images.githubusercontent.com/9842899/121658898-f73bdf00-cacb-11eb-8a57-ee055a1f284e.PNG)

On the console, it prints:

```
[error] (Parsing) Missing field 'nickname' in class Participant
```

I already fixed for further using, but for this particular account, it's kinda too late to fix it since it seems that the empty string has already been recorded although I've changed the user name to not be empty. 

So in summary, the steps to reproduce are:
1. Feature developed in Android first, with nickname set with format `[name] ([role] / [userID])`.
2. The user without a username, accessed the Crisp chat page on Android first. Nickname recorded as ` ([role] / [id]` (a space at the beginning is because the name is empty. Then send a message from Android.
3. Feature developed in iOS then, with nickname set with format `[name]`.
4. The same user opens Crisp chat page on iPhone, at first open it behaved normally.
5. The user close the page on iPhone.
6. The user open the Crisp chat page again on iPhone.
7. The error alert appeared, and the error message `[error] (Parsing) Missing field 'nickname' in class Participant` showed on console.

The problem is that in Android, the error doesn't shown, but only in iOS version. Please help me solve this issue. Thanks!

**Comment by kennethvl** [comment]
A bit update with this issue.

I encountered another error: 

```[error] (Parsing) Found incorrect type for field 'content' in class ChatMessage. Expected 'String', found __NSDictionaryM instead.```

Here are the steps to reproduce it:
1. Open Crisp chat page initially in iOS
2. Send a message from iOS
3. Close Crisp chat page on iOS
4. With the same user, open Crisp chat page from Android.
5. Send a message from Android
6. Close Crisp chat page on Android
7. Reopen Crisp chat page on iOS
8. Alert appeared "Error starting chat" with the message showed on console log as above.

**Comment by kennethvl** [comment]
Anyway, I used the same token ID on both Android and iOS (I'm using the user ID) when the error occurred.

When I set a different token ID on iOS (adding "-ios" after the userID), the error doesn't show, although there will be two conversations on the Crisp dashboard.

**Comment by nesium** [comment]
Hi @kennethvl. Thanks for your report. The first issue has been addressed in [the latest version of the SDK](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.0.14). Unfortunately the second issue will require an update to the [Android SDK](https://github.com/crisp-im/crisp-sdk-android), which is already in the works and should be published shortly. So please keep an eye out for that as well.
