### ISSUE TITLE
Chat history is specific per device and not identified by token_id

### ISSUE THREAD

**Issue by mohamedabady** [crisp-im/crisp-sdk-ios#48]
chat history in the chat box is it identified by token_id or identified by device ?

scenario : 
- reach for support from email1 with token1 from device1.
- get history of email1 correctly
- logging in with email2 and token2 in the same device1
- reach for support again with email2
- get chat history for email1 :(

what to be concluded that chat history is identified by Device... 
need to fix this issue 
and if possible give use clear implementation  guide to know how tackle this issue

@baptistejamin

**Comment by baptistejamin** [comment]
Hello!


By default it's identified by the device.


If you use the token_id, then it's identified via the token_id :)

**Comment by mohamedabady** [comment]
@baptistejamin i do set token_id as uniquely identified user id .. but this didn't solve the problem

**Comment by baptistejamin** [comment]
When setting the token_id, your history is not recovered?

**Comment by mohamedabady** [comment]
@baptistejamin no unfortunately, it's not recovered. What ever chat history exists on the device keeps appearing again with no relation to current user

**Comment by baptistejamin** [comment]
We are looking at this issue with the dev team

**Comment by baptistejamin** [comment]
We'll have an anwser soon

**Comment by mohamedabady** [comment]
history is specific per device. when logging with different email, i get the history of the previous user on the device. it happens on android and IOS devices

**Comment by mohamedabady** [comment]
@baptistejamin @nesium any updates on this issue?

**Comment by imougy** [comment]
Changing the email doesn't change the history.  It seems the history is linked to the device and doesn't honor user email.
Sad :(

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
