### ISSUE TITLE
Chat content | documents (e.g: .pdf) is not available to open through chat on device

### ISSUE THREAD

**Issue by mohamedabady** [crisp-im/crisp-sdk-ios#49]
when support send a document to users, the link is presented as plain text and it's not clickable. But on the dashboard side links appear as hyperLinks and open normally 

<img width="232" alt="Screen Shot 2021-06-17 at 12 16 05 PM" src="https://user-images.githubusercontent.com/47719144/122377965-d4934580-cf65-11eb-854e-2c3c37677212.png">
<img width="798" alt="Screen Shot 2021-06-17 at 12 18 25 PM" src="https://user-images.githubusercontent.com/47719144/122378301-25a33980-cf66-11eb-97ca-4590f00a2522.png">

**Comment by baptistejamin** [comment]
Hello!


Your screenshot is for Android. The issue you are having is for iOS or Android ? Both?

**Comment by mohamedabady** [comment]
@baptistejamin it's not working on both android and IOS
![Simulator Screen Shot - iPhone 12 - 2021-06-17 at 12 33 39](https://user-images.githubusercontent.com/47719144/122380583-51272380-cf68-11eb-8e40-4ddc8cb5bed4.png)

**Comment by baptistejamin** [comment]
Thank you for your report

**Comment by mohamedabady** [comment]
@baptistejamin is this issue solved? so we closed it?
