### ISSUE TITLE
chat docs | documents on storage expire quickly

### ISSUE THREAD

**Issue by mohamedabady** [crisp-im/crisp-sdk-ios#50]
we have documents uploaded on crisp storage. When a user or support admin try to access these documents we receive a message that documents are expired. These documents are uploaded in less than 2 month.
<img width="1535" alt="Screen Shot 2021-06-17 at 12 48 49 PM" src="https://user-images.githubusercontent.com/47719144/122394949-ca2d7780-cf76-11eb-9c3c-2a6122702764.png">

**Comment by baptistejamin** [comment]
This issue is not related the iOS SDK. 


For safety reasons, files uploaded on Crisp are autodeleted after some time

**Comment by mohamedabady** [comment]
is there an alternative to store our documents?
