### ISSUE TITLE
Problems with Arabic Language iOS SDK

### ISSUE THREAD

**Issue by iTarek** [crisp-im/crisp-sdk-ios#54]
Hello
My App works on Arabic no matter the device local, I did not find a way to set the Crisp SDK local, tried 
`CrispSDK.locale = NSLocale(localeIdentifier: "ar") as Locale`
But it's not working

If I changed the device language to Arabic, the Crisp SDK detect the device local language and works in Arabic but there are few bugs...

The 'Starting Chat...' message always in English
![IMG_2063](https://user-images.githubusercontent.com/693715/129088909-cb75b718-0b3d-415c-b471-c2685641fe1c.PNG)

There is a problem with the close button overlap the header text, also the header text not on the correct place it's far on the right without margin like the other LTR languages.
![IMG_46A275110549-1](https://user-images.githubusercontent.com/693715/129089157-a342160c-f1ea-4356-85b1-dd2d3d384c4a.jpeg)
Also there is words on English like Tap to set your email

And if you click on the arrow near the set your email, the email field go out of the screen
![IMG_9DD2CBBA0243-1](https://user-images.githubusercontent.com/693715/129089957-af17209b-1f4b-419c-95d6-e90730413d46.jpeg)

Also when long press on a message, the text is not localized, And what is the 'system' name near the moderator icon?
Also notice that the date is wrong
![IMG_992AF5C9D912-1](https://user-images.githubusercontent.com/693715/129092814-d0cd383f-6827-4d36-91af-96642d716bb3.jpeg)

There is more bugs, but the most important thing is be able to set the Crisp SDK language no matter the device language.

Thank you

**Comment by baptistejamin** [comment]
Is this React Native?

**Comment by baptistejamin** [comment]
Can you please send us a screen recording showing the issues?

**Comment by iTarek** [comment]
> Can you please send us a screen recording showing the issues?

No problem I will do that, Just it's so important to have a way to change the Crisp SDK language away from user device language, is there a way to do that?

**Comment by baptistejamin** [comment]
I would need to verify this with the tech team and show the other bugs reported at the same time once screen recording is sent.

**Comment by iTarek** [comment]
Here you are a Video for most of the bugs when using Arabic, but I had to change the all device language to Arabic to use the SDK in Arabic, as I said you should have a way to change the SDK language.

https://www.dropbox.com/s/riafpt6jidvo6cd/RPReplay_Final1628719091.MP4?dl=0

Thank you for your help and I wish if you can solve this problem soon and we will recommend your service to all Arabic developer community.

I also can help for free to bring the Contact Form in Arabic, Just send the localize strings in English and I will translate it to Arabic, it's so Important to have Contact From in Arabic to be able use unified inbox in the best way.

**Comment by baptistejamin** [comment]
Thank you for all this. We will get back to you with updates asap.

**Comment by iTarek** [comment]
I know that you get header background from the backend also get the default welcome message, why not get the language from the backend too?

**Comment by iTarek** [comment]
Can we have update soon so I can include Crisp with our next update

**Comment by iTarek** [comment]
Any update?

**Comment by abdulazizSi** [comment]
I am waiting for an update as well 🤩

**Comment by EssamSoft** [comment]
@baptistejamin 
I have same problem and it's very important for us, please solve this bug ASAP

Thank you

**Comment by baptistejamin** [comment]
Hi, our agents are offline at the moment. Please leave a message and we will get back to you as soon as possible.

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!

**Comment by iTarek** [comment]
After making 'locale' is deprecated: locale is no longer available
`CrispSDK.locale = NSLocale(localeIdentifier: "ar") as Locale`

is there anyway to force the CrispSDK to use a language?
