### ISSUE TITLE
[BUG] The button picker doesn't shown on mobile

### ISSUE THREAD

**Issue by pedy4000** [crisp-im/crisp-sdk-ios#58]
Hi
I run a scenario in the bot plugin but the button picker doesn't show on mobile

button picker in my desktop:
<img width="300" alt="Screen Shot 2021-09-16 at 12 54 08 PM" src="https://user-images.githubusercontent.com/16068346/133586482-85c9eaa9-67ff-488f-9fae-5a4e7c511628.png">

button picker in my mobile:
<img width="300" alt="photo_2021-09-16 13 55 58" src="https://user-images.githubusercontent.com/16068346/133587225-e9e25058-4763-4036-a85f-872b3af8e8ce.jpeg">
my mobile is an iPhone xs and I test it with safari, chrome, brave
also, I test it in another mobile like iPhone6
even I clear my cache and it's not work

if you want to test it 
you can go to www.rabincash.com
and send "crisp" in the chatbox

sorry for my bad English

**Comment by eliottvincent** [comment]
Hello, are you using the iOS SDK? Your second screenshot looks like the web version of our chatbox.

**Comment by pedy4000** [comment]
yes i using iOS SDK,
also i test it with android SDK
<img width="300" alt="photo_2021-09-16 19 13 12" src="https://user-images.githubusercontent.com/16068346/133633093-20df40a1-d729-4a08-8289-132bf4eca8b6.jpeg">

**Comment by eliottvincent** [comment]
This is not the iOS SDK nor the Android SDK. Your are using the regular, web version of our chatbox.
Please ask this question to our support: https://crisp.chat/en/contact/

**Comment by pedy4000** [comment]
I have talked to Clark from crisp before
and he told me to issue my problem on this Github repository

sorry about ios SDK, I wrote wrong
those three photos are from the web version of chat box from Desktop, ios and android
