### ISSUE TITLE
Error occurred while opening a chat controller

### ISSUE THREAD

**Issue by DrashtiJaviya-Openxcell** [crisp-im/crisp-sdk-ios#61]
iOS SDK version:   Crisp (1.0.6, 1.1.0)

For some users, Crisp Chat SDK is giving the following error:

[error] (Server)Invalid WebsiteId

[error] A websocket error occurred. [“Connection closed by server. Code=1000, type=protocolError”]

We follow the below steps for Integration
1. Set Website in didFinishLaunchingWithOptions

`CrispSDK.configure(websiteID: crispWebsiteId)`

2. set Token Id before opening chat controller 

`CrispSDK.setTokenID(tokenID: "\(userID)-\(WebServiceHandler.shared().objUserModel.crispToken ?? "")")
`

Also, We tried to set again websiteId, token, Email, and Nickname before present chat controller

`self.present(ChatViewController(), animated: true, completion: nil)`

For the iOS application, we tried with two versions and both had the same response.

![Crisperror2](https://user-images.githubusercontent.com/46279724/137911803-2e41d637-ae72-4582-8bec-96895325e61d.png)
![CrispError3](https://user-images.githubusercontent.com/46279724/137911832-5421f503-88aa-4f48-9cad-58df464a22f4.png)
We are facing this issue only for some users and here we mention one of our user details. All other users are working fine. This means for all other users, we are able to chat from the application without getting any errors.

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
