### ISSUE TITLE
[Crash] SocketIO.SocketManager.init

### ISSUE THREAD

**Issue by amitdizvik2021** [crisp-im/crisp-sdk-ios#62]
In my app already implemented Socket. when we implemented in Crisp chat in our app then my app is crashing.
I am using Latest xcode version 13.1. Please let me know for valuable answer.

Thanks in Advance.

    0x1071f27f3 <+19>: callq  0x107220482               ; symbol stub for: objc_allocWithZone
    0x1071f27f8 <+24>: movq   %rbx, %rdi
    0x1071f27fb <+27>: movq   %r14, %rsi
    0x1071f27fe <+30>: movq   %rax, %r13
    0x1071f2801 <+33>: callq  0x1071f2820               ; SocketIO.SocketManager.init(socketURL: Foundation.URL, config: SocketIO.SocketIOClientConfiguration) -> SocketIO.SocketManager at SocketManager.swift:144
->  0x1071f2806 <+38>: addq   $0x8, %rsp
    0x1071f280a <+42>: popq   %rbx
    0x1071f280b <+43>: popq   %r13
    0x1071f280d <+45>: popq   %r14
    0x1071f280f <+47>: popq   %rbp
    0x1071f2810 <+48>: retq

**Comment by ritz122** [comment]
facing the same issue.. did you find any solution?           

in our app we are using our own socket and it was working fine before intigration crist sdk.. after crisp sdk intigration app is crashing when we are trying to connect socket

 Please help if there is any solution

**Comment by nesium** [comment]
This was fixed in the 1.2.0 release
