### ISSUE TITLE
[Crash] SocketIO.SocketManager.init #62

### ISSUE THREAD

**Issue by amitdizvik2021** [crisp-im/crisp-sdk-ios#63]
In my app already implemented Socket. when we implemented in Crisp chat in our app then my app is crashing.
I am using Latest xcode version 13.1. Please let me know for valuable answer.

Thanks in Advance.

0x1071f27f3 <+19>: callq  0x107220482               ; symbol stub for: objc_allocWithZone
0x1071f27f8 <+24>: movq   %rbx, %rdi
0x1071f27fb <+27>: movq   %r14, %rsi
0x1071f27fe <+30>: movq   %rax, %r13
0x1071f2801 <+33>: callq  0x1071f2820               ; SocketIO.SocketManager.init(socketURL: Foundation.URL, config: SocketIO.SocketIOClientConfiguration) -> SocketIO.SocketManager at SocketManager.swift:144

**I was already Submit this issue but not getting any reply. I am resubmitting again same issue.
My old issue link are given below:**
[https://github.com/crisp-im/crisp-sdk-ios/issues/62]

**Comment by baptistejamin** [comment]
Closing (duplicate)

**Comment by amitdizvik2021** [comment]
I was posted issue on 3rd nov but not getting reply yet, So I was talk to your support executive He says resubmitted the issue. Then I did resubmit this issue again. But please reply ASAP... I am using latest xcode version and iOS version also. I am frustrated.
Please solved it ASAP.
Thanks in Advance!!!!!!!!
