### ISSUE TITLE
MacCatalyst support broke

### ISSUE THREAD

**Issue by ZComwiz** [crisp-im/crisp-sdk-ios#66]
When switching to xcframework style distro, it appears that MacCatalyst no longer works because MacCatalyst requires its own slices.

Here are some options to fix it:
https://onesignal.com/blog/mac-catalyst-fat-framework/
and
https://developer.apple.com/forums/thread/120542

**Comment by ZComwiz** [comment]
@baptistejamin — any plans to fix this?

**Comment by ZComwiz** [comment]
@nesium have you looked into this?

**Comment by nesium** [comment]
Hi @ZComwiz. Version 1.3.0 now contains a Mac Catalyst slice.

**Comment by ZComwiz** [comment]
@nesium not all heroes wear capes (but its chill if you do 🦸)

Thanks Marc!

**Comment by ZComwiz** [comment]
Hey @nesium, quick followup— have you tried building to Mac Catalyst? I am getting this error now:

` /Contents/Frameworks/Crisp.framework: bundle format is ambiguous (could be app or framework)`

**Comment by nesium** [comment]
HI @ZComwiz. I did, with a local build. Apparently when zipping the framework symlinks were resolved which trips up code signing. Furthermore when running on an M1 Mac and integrating the framework via Swift PM I did only see that as a warning. Could you please try again and see if version 1.3.1 fixes the issue?

**Comment by ZComwiz** [comment]
It is being included via cocoapods. Trying to test it now

**Comment by ZComwiz** [comment]
It works! Thanks @nesium!

**Comment by nesium** [comment]
Glad to hear that it works!
