### ISSUE TITLE
App crash when connecting to socket 

### ISSUE THREAD

**Issue by ritz122** [crisp-im/crisp-sdk-ios#67]
i am using socket in my application and it was working fine before Crisp sdk intigration..

After intigarting CRISP sdk, app is crashing when trying to connect socket..
[https://drive.google.com/file/d/16pAnqb2T8wKKJDnc1l1RcSr1EhogrczZ/view](url)

Please look into this issue as soon as possible...

Any help would be much appreciated.

#62 check this issue and ask for help from Crisp support for same issue..however executive suggest me to re-submit the same issue...

**Comment by nesium** [comment]
Hi @ritz122. Could you please try with the [1.2.0-beta.1](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.2.0-beta.1) release and see if the issue persists? Thank you!
