### ISSUE TITLE
Keyboard covering the message box while typing

### ISSUE THREAD

**Issue by halmg** [crisp-im/crisp-sdk-ios#68]
Our customer support team has been receiving a number of complaints from our users that when they are using our chat platform, when sending messages to us, the keyboard obscures what they are trying to type, thus making it difficult for them to formulate their message. Is this a known issue from your side? And is there anything we can do from our side in order to fix it?

We have looked into troubleshoot topics available on your help site but none of them match and answer this issue.

We have also been in contact with your customer support, that directed us here. We will appreciate your help, and thanks in advance.

Here is an example of what we are referring to, sent by one of our users.

https://user-images.githubusercontent.com/9902894/153581264-2ff4e5ff-c90d-4836-9d19-35617bd72451.mov

**Comment by JMCPH** [comment]
Experiencing the same thing. Any update @baptistejamin ?

**Comment by nesium** [comment]
Thanks for your report and the video @halmg.

I believe that I was able to reproduce the issue. This situation could happen when pulling the presented ChatViewController down slightly, releasing and tapping the textfield quickly afterwards.

We've resolve the issue in the [1.2.0 release](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.2.0).

Please let us know in case you're still seeing the issue after upgrading, ideally with steps to reproduce.
