### ISSUE TITLE
Crisp Swift Package Manager invalid manifest

### ISSUE THREAD

**Issue by lucasvercelot** [crisp-im/crisp-sdk-ios#70]
Hello,

Trying to use Crisp (1.3.2) by adding it as a Swift Package (with SPM) results to this error :

`invalidManifestFormat("/var/folders/3k/g3x2z5pj2fg9ft2f8vv94mj0f9wgmb/T/TemporaryFile.sqkCga.swift:13:17: error: unterminated string literal\n      checksum: \"warning: Usage of /Users/mb/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/mb/Library/org.swift.swiftpm/configuration/collections.json instead.\n                ^\n/var/folders/3k/g3x2z5pj2fg9ft2f8vv94mj0f9wgmb/T/TemporaryFile.sqkCga.swift:14:3: error: \'b\' is not a valid digit in integer literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n  ^\n/var/folders/3k/g3x2z5pj2fg9ft2f8vv94mj0f9wgmb/T/TemporaryFile.sqkCga.swift:14:65: error: unterminated string literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n                                                                ^\n/var/folders/3k/g3x2z5pj2fg9ft2f8vv94mj0f9wgmb/T/TemporaryFile.sqkCga.swift:12:95: error: missing argument for parameter \'checksum\' in call\n      url: \"https://github.com/crisp-im/crisp-sdk-ios/releases/download/1.3.2/Crisp_1.3.2.zip\",\n                                                                                              ^\n                                                                                              , checksum: <#String#>\nPackageDescription.Target:78:24: note: \'binaryTarget(name:url:checksum:)\' declared here\n    public static func binaryTarget(name: String, url: String, checksum: String) -> PackageDescription.Target\n                       ^", diagnosticFile: Optional(<AbsolutePath:"/Users/l.vercelot/Library/Developer/Xcode/DerivedData/Liberation-cyupajqcvtygweawtmfedgjtkzfc/SourcePackages/ManifestLoading/crisp-sdk-ios.dia">)) in https://github.com/crisp-im/crisp-sdk-ios.git`

**Comment by nesium** [comment]
Hi @lucasvercelot. I've replaced 1.3.2 with a working version. You should now be able to update the Swift package in Xcode.
