### ISSUE TITLE
Xcode 13.2 Could not resolve Crisp-sdk-ios

### ISSUE THREAD

**Issue by vixtorlucas** [crisp-im/crisp-sdk-ios#71]
I'm having a problem with crisp-sdk-ios and would like some help with that. I've being using crisp chat for a while in the company that I work, and yesterday when we was building the application on the CI/CD environment it was not being able to resolve. I did some tests locally and it was working fine until I remove the framework from the project and add it again. Now I'm not being able to use SPM to it, it keeps saying that Crisp-IOS-SDK can't be resolved and I'm not sure what can I do for that.

this is the output on CI/CD env:

`invalidManifestFormat("/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:13:17: error: unterminated string literal\n      checksum: \"warning: Usage of /Users/mb/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/mb/Library/org.swift.swiftpm/configuration/collections.json instead.\n                ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:14:3: error: \'b\' is not a valid digit in integer literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n  ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:14:65: error: unterminated string literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n                                                                ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:12:95: error: missing argument for parameter \'checksum\' in call\n      url: \"https://github.com/crisp-im/crisp-sdk-ios/releases/download/1.3.2/Crisp_1.3.2.zip\",\n                                                                                              ^\n                                                                                              , checksum: <#String#>\nPackageDescription.Target:76:24: note: \'binaryTarget(name:url:checksum:)\' declared here\n    public static func binaryTarget(name: String, url: String, checksum: String) -> PackageDescription.Target\n                       ^", diagnosticFile: Optional(<AbsolutePath:"/Users/distiller/Library/Developer/Xcode/DerivedData/********-cebtjamhvzvoqrchdawjrkktjxhc/SourcePackages/ManifestLoading/crisp-sdk-ios.dia">)) in https://github.com/crisp-im/crisp-sdk-iosxcodebuild: error: Could not resolve package dependencies:
  invalidManifestFormat("/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:13:17: error: unterminated string literal\n      checksum: \"warning: Usage of /Users/mb/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/mb/Library/org.swift.swiftpm/configuration/collections.json instead.\n                ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:14:3: error: \'b\' is not a valid digit in integer literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n  ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:14:65: error: unterminated string literal\n02bae47d1a03204665b4604fa9e385870b33a3ac0f7ed4693ee8b2b26f9e1537\"\n                                                                ^\n/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/TemporaryFile.Qh99En.swift:12:95: error: missing argument for parameter \'checksum\' in call\n      url: \"https://github.com/crisp-im/crisp-sdk-ios/releases/download/1.3.2/Crisp_1.3.2.zip\",\n                                                                                              ^\n                                                                                              , checksum: <#String#>\nPackageDescription.Target:76:24: note: \'binaryTarget(name:url:checksum:)\' declared here\n    public static func binaryTarget(name: String, url: String, checksum: String) -> PackageDescription.Target\n                       ^", diagnosticFile: Optional(<AbsolutePath:"/Users/distiller/Library/Developer/Xcode/DerivedData/********-cebtjamhvzvoqrchdawjrkktjxhc/SourcePackages/ManifestLoading/crisp-sdk-ios.dia">)) in https://github.com/crisp-im/crisp-sdk-ios`

and on SPM Manager I got this:
<img width="665" alt="Captura de Tela 2022-03-30 às 11 39 29" src="https://user-images.githubusercontent.com/16263094/160862404-77613192-9cbe-41ca-8baa-4a7b75701cc9.png">

did someone faced I issue like that before?

**Comment by frboulais** [comment]
Same here, I had to use CocoaPods!
