### ISSUE TITLE
SDK Crashes when ChatViewController is presented and the app is put into background

### ISSUE THREAD

**Issue by lucasvercelot** [crisp-im/crisp-sdk-ios#72]
Hello,

When the SDK Crisp is presented (ChatViewController), if I put the app into background, the SDK crashes with the following error : 
`dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Crisp.BannerViewController 0x10811a890> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key supportButton.'
terminating with uncaught exception of type NSException`

It looks like some outlet ("_supportButton_") is missing somewhere.

According to the Exception Backtrace, it seems to be happening after the method "_ChatContentViewController.updateBannerView()_" is called.

### Project Context :

The project in which I have this crash was first created in late 2018 with the original app delegation (AppDelegate) methods, not the new scenes delegation (SceneDelegate) methods that appeared a few years ago.
Plus, I had to change the target deployment to iOS 13 minimum to integrate the CrispSDK.

Also, I would like to inform you that when I create a brand new Xcode project with Xcode 13.2, I don't have this crash.
Do you have any idea why I have this problem in my project, have you, by any chance, seen this in some particular conditions ?

Thank you.

**CrispSDK** version used : **1.4.0** (installed via Cocoapods)
**Xcode** version used : **13.2**
**Device/iOS** version used : **iPhone 11 on iOS 15.3.1**

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
