### ISSUE TITLE
Xcode 14 Beta 5 - The app references non-public selectors

### ISSUE THREAD

**Issue by JMCPH** [crisp-im/crisp-sdk-ios#75]
**Description**
We are experiencing issues when uploading our app to the AppStore.
It seems like the `Crisp.framework` is using non-public selectors, which is not allowed by Apple.

**Error message**
Error: The app references non-public selectors in Payload/tiimo.app/Frameworks/Crisp.framework/Crisp: setInputImage

**Screenshot**
<img width="744" alt="Screenshot 2022-08-18 at 11 19 37" src="https://user-images.githubusercontent.com/5514628/185360649-7ca271f6-7d7f-4e18-b157-b7f195e80274.png">

We are highly dependent on being able to upload to TestFlight using the Xcode 14 Beta, in order to be prepared for the iOS 16 release.

**Comment by DavidDHansson** [comment]
I'm having the same issue, please prioritize!

**Comment by JMCPH** [comment]
@baptistejamin @nesium @valeriansaliou can you please take a look at this? It's an extremely critical bug, as we can't upload app versions to TestFlight for the new iOS 16 features.

**Comment by nesium** [comment]
Hey there. Thanks for bringing this to our attention. That seems like an issue in the Xcode beta since we were not using any private APIs as implied by the App Store error. Anyways, [version 1.6.3](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.6.3) fixes the issue.
