### ISSUE TITLE
Failed to build module 'Crisp'; this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by DURODOLA-ABDULKABIR** [crisp-im/crisp-sdk-ios#76]
AppDelegate error: Failed to build module 'Crisp'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.

**Comment by nesium** [comment]
Hi @DURODOLA-ABDULKABIR. Sorry about that. Unfortunately a release built with an Xcode beta slipped through the cracks. This is fixed in 1.6.4.
