### ISSUE TITLE
Starting chat error in SwiftUI

### ISSUE THREAD

**Issue by YaoKevinn** [crisp-im/crisp-sdk-ios#79]
I am implementing this on a SwiftUI project. And when app launch, it always open successfully for the first time and then when i close the chat and open for the second time, it gets stuck on the "Starting chat" loading screen and through console it throws error:
**[error] We could not connect to the chat. Try again now, or later.**
After it fails and i open for the third time and it works again, then the fourth fails again and so on.
I am implementing the ChatViewController like this, not sure if it is the best solution for SwiftUI project:
<img width="694" alt="圖片" src="https://user-images.githubusercontent.com/51725053/211055173-b8ba79c4-63ec-40b3-ac1a-5a85afb0e2d7.png">
View:
<img width="244" alt="圖片" src="https://user-images.githubusercontent.com/51725053/211055239-b70aebbb-d62d-4a8e-a69c-41e28a6ca716.png">

**Comment by baptistejamin** [comment]
Did you set your website ID?
--
Baptiste Jamin

**Comment by YaoKevinn** [comment]
Hi, Yes, I set the website ID on app launch. However you gave me the idea to make some fixes and is working now! 
Some how closing the chat erase the website ID, so i make sure that it is set again every time when open chat button is clicked. 

Thanks a lot!
Best regards
