### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by nseb** [crisp-im/crisp-sdk-ios#80]
Hello , 
I try to integrate with IOS but there is no close or back button ?
![gnome-shell-screenshot-eja6a3](https://user-images.githubusercontent.com/6363226/220379860-7ff19979-ba30-4d64-857e-5d8d0f9fb1f0.png)

Best Regards

**Comment by nesium** [comment]
Hi @nseb. Thanks for the report. The idea was that it isn't needed since you can just pull down the ViewController. But you're right we'll add one in the next release.

**Comment by nesium** [comment]
Hi @nseb. I'm happy to report that a close button has been added in [2.2.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.2.0).

**Comment by nseb** [comment]
Thanks
