### ISSUE TITLE
Message with Help desk link

### ISSUE THREAD

**Issue by nseb** [crisp-im/crisp-sdk-ios#81]
Hello , 
If I send a Help desk link from Inbox team to the chat box of a user, the link is open like a web link, it is not possible to open as when you click in the Help Desk directly from the Messenger ?

**Comment by baptistejamin** [comment]
Hello crisp-sdk-ios#81!

Jairo here, pleased to help you :)

Please send a screenshot of how it should look for us to better understand.

**Comment by nesium** [comment]
Hi @nseb. That's an oversight on our part. We've recently changed the behavior when you're browsing the Helpdesk and click on a link to another article to stay within the Helpdesk and not open the external browser. That behavior is missing when you tap a link in the chat - as you've described - and will be added in a future release.

**Comment by nesium** [comment]
Hi @nseb. I'm happy to report that Helpdesk links open in the Helpdesk tab starting from [2.3.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.3.0).
