### ISSUE TITLE
Error typing the message

### ISSUE THREAD

**Issue by h-o-sein** [crisp-im/crisp-sdk-ios#83]
Hello
Error typing the message
version Crisp: 2.2.1
with: SwiftUI
Video:

https://user-images.githubusercontent.com/9271127/230393460-9d3b6764-99a5-47e3-b919-a0e8b904ed01.mov

**Comment by baptistejamin** [comment]
Hi, Alexandre from the Crisp team! Thank you for sharing this bug with us. Can you share the iPhone you use, its version, and the version of the Crisp IOS app you use, please?

**Comment by h-o-sein** [comment]
Version SDK Crisp: 2.2.1
Version iOS: 16.4
Version xCode: 14.3

**Comment by nesium** [comment]
Hi @h-o-sein. Thanks for the report! 
Is it possible that you're presenting the Crisp SDK in a SwiftUI context? If so I'd urge you to use the new `ChatView`. Here's a quick example…

```swift
struct ContentView: View {
  @State var isChatPresented = false

  init() {
    CrispSDK.configure(websiteID: "YOUR_WEBSITE_ID")
  }

  var body: some View {
    VStack {
      Button("Show chat") {
        self.isChatPresented = true
      }
      .sheet(isPresented: self.$isChatPresented) {
        ChatView()
      }
      .padding()
    }
  }
}
```

**Comment by h-o-sein** [comment]
Thanks, the problem is solved
