### ISSUE TITLE
Unable to programmatically switch to Chat view after displaying Helpdesk view

### ISSUE THREAD

**Issue by nicolasmarchal** [crisp-im/crisp-sdk-ios#86]
Overview:
I am using the crisp-sdk-ios library in my application to provide a chat support to users. The library offers two main view - the chat view and the helpdesk view. By default, when presenting the `ChatViewController`, the Chat view is presented. However, there is a functionality to specify that we want to display the Helpdesk view instead, with the call of `searchHelpdesk` or `openHelpdeskArticle`

Problem:
After setting the SDK to display the Helpdesk view, there seems to be no straightforward way to programmatically switch back to the chat view once the Helpdesk view has been displayed and closed by the user. The library seems to save the last view that was displayed (in this case, the HelpDesk view), and there's no exposed method or API to force the view to go back to the Chat view programmatically.

Steps to Reproduce:

- Call `searchHelpdesk` then present the `ChatViewController`.
- Observe that the HelpDesk view is displayed as intended.
- Dismiss the `ChatViewController`
- Representing a new instance of the `ChatViewController` without calling `searchHelpdesk`
=> Notice that the last view loaded from `searchHelpdesk` or `openHelpdeskArticle` is opened again inside the `ChatViewController`

Expected Behavior:
Ideally, the library should provide a way to programmatically switch between the Chat view and the HelpDesk view even after the initial launch.

Additional Information:
I have explored the library's documentation and source code, and there seems to be no public API or method to force the view back to the Chat. It's possible that this could be an oversight or a missing feature in the library.

Environment:
iOS version: iOS 16.5.1
Chat Support library version: 2.3.1
Xcode version: 14.3.1
Device tested on: iPhone 11

**Comment by nesium** [comment]
Hi @nicolasmarchal. Thanks for your report! This sounds like an oversight indeed. We'll look into it!

**Comment by nesium** [comment]
Hi @nicolasmarchal. [Version 2.4.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.4.0) now includes [a new method](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/openchat()) to switch back to the Chat view. 

I hope this resolves your issue. Otherwise feel free to reopen this issue if you have any further questions.
