### ISSUE TITLE
Add callback for dismissal

### ISSUE THREAD

**Issue by levi** [crisp-im/crisp-sdk-ios#87]
Currently, there's no way to receive a callback when the modal is dismissed. Simplest solution would be to make the ChatViewController not `final` and let me subclass it to add my own callbacks.

**Comment by nesium** [comment]
Hi Levi. Thanks for the report.

You can indeed [add a callback](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/addcallback(_:)). It looks a bit unusual because it matches the web API but does what you're looking for…

```swift
_ = CrispSDK.addCallback(.messageSent { message in
  print("Message sent", message)
})
```

Feel free to reopen if you have further questions.
