### ISSUE TITLE
Chat view controller header takes up entire available space in landscape orientation

### ISSUE THREAD

**Issue by levi** [crisp-im/crisp-sdk-ios#88]
The chat view controller is effectively unusable on iPhone 14 Pro Max screen resolution in a landscape orientation. 

Simplest solution would be to force the view controller orientation to portrait, but the ChatViewController is exported as `final` and no edits can be made.

**Comment by nesium** [comment]
Hi Levi. Thanks! We'll look into that.

**Comment by nesium** [comment]
Hi @levi. [Version 2.4.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.4.0) should now be usable in a landscape orientation.

I hope this resolves your issue. Otherwise feel free to reopen this issue if you have any further questions.
