### ISSUE TITLE
Messaging is Unavailable

### ISSUE THREAD

**Issue by muhammadsaddamnur** [crisp-im/crisp-sdk-ios#89]
I have an issue where the text field doesn't want to be inputted and the message 'Messaging is Unavailable' appears as shown in the screenshot below. How can I fix this?

![Screenshot 2023-08-08 at 14 34 38](https://github.com/crisp-im/crisp-sdk-ios/assets/22446388/cf057279-31f1-48b7-bbb0-9d9f9c1896e6)

**Comment by nesium** [comment]
Hi @muhammadsaddamnur.

There are multiple website settings that can lead to this. A few examples include:

1. You're forcing visitors to identify themselves and at least one message has been posted by a visitor in the chat.
2. You've placed support in vacation mode
3. You've blocked certain countries/locales

<img width="660" alt="Screenshot 2023-08-08 at 10 46 51" src="https://github.com/crisp-im/crisp-sdk-ios/assets/39174/9ad5c391-ff17-47dd-8fd4-1b9488a9b15a">

There might be other settings as well which lead to this result. Are you using the [web widget](https://crisp.chat/en/livechat/) as well? Do you have the same result there?

**Comment by muhammadsaddamnur** [comment]
Great, it seems to be solved. The issue was with the enabled 'Place support in vacation.' 
But why is there no issue with the Crisp Android SDK, unlike in iOS?

**Comment by nesium** [comment]
I'm glad to hear that it's solved now. I have just spoken to our Android developer and it seems that this is a missing feature in the Android SDK which will be added in an upcoming version. Since the iOS SDK behaves correctly in that regard I'm going to close this issue. Feel free to reopen if you have any further questions.
