### ISSUE TITLE
Support for reverse proxy for crisp

### ISSUE THREAD

**Issue by henrychan-osl** [crisp-im/crisp-sdk-ios#96]
Pre request of business 
we have implemented the reverse proxy from 
https://help.crisp.chat/en/article/how-can-i-add-my-helpdesk-behind-a-reverse-proxy-ar5km0/

We add it in the nginx like this

$server_name = <domain name>

`location /support/ {
        proxy_pass https://<crisp custom domain>/en/;
        proxy_http_version 1.1;

        proxy_ssl_server_name on;

        proxy_set_header Accept-Encoding "";
        proxy_set_header Access-Control-Allow-Origin "*";

        sub_filter 'href="https://$server_name/' 'href="https://$server_name/';

        sub_filter 'action="https://<crisp custom domain>/en/' 'action="https://$server_name/support/';

        sub_filter 'href="https://<crisp custom domain>/en/' 'href="https://$server_name/support/';
        sub_filter 'href="https://<crisp custom domain>/zh/' 'href="https://$server_name/zh-Hans/support/';
        sub_filter 'href="https://<crisp custom domain>/zh-hk/' 'href="https://$server_name/zh-Hant/support/';

        sub_filter 'hreflang="zh"' 'hreflang="zh-Hans"';
        sub_filter 'hreflang="zh-hk"' 'hreflang="zh-Hant"';

        sub_filter 'href="/en/' 'href="/support/';
        sub_filter 'href="/zh/' 'href="/zh-Hans/support/';
        sub_filter 'href="/zh-hk/' 'href="/zh-Hant/support/';
        sub_filter 'action="/en/' 'action="/support/';

        sub_filter_once off;
    }`
    
    you can see I like to change the /en/ to /support/, /zh/ to /zh-Hans/support/  and /zh-hk/ to /zh-Hant/support/
    
it is actually implemented in osl.com/support/. 

I used this library from our app as well. yet once we use the chatbot in library.
it is using pointing to https://<web domain>/article/<XYZ> instead of https://<crisp custom domain>/article/<XYZ> 
and it leads to 404 error.

I like to understand how to fix the issue from library level instead of adding a 301 from  https://<web domain>/article/<XYZ> to 
https://<web domain>/support/article/<XYZ>.  (that's what we did to temporary fix it)

**Comment by eliottvincent** [comment]
Not related to iOS SDK, closing.

**Comment by henrychan-osl** [comment]
your SDK use the wrong path. how it is not related to SDK.  what is it related to?

**Comment by eliottvincent** [comment]
Our iOS SDK will use your regular helpdesk domain. There is no way to specify another URL.
