### ISSUE TITLE
Chatview gets freeze

### ISSUE THREAD

**Issue by reygie25** [crisp-im/crisp-sdk-ios#97]
The chatview freezes while typing, I can't even tap the close button and it will make the whole app freeze. Please check the video

Here's the pod I used. Also, there were no logs in Xcode regarding the crisp when I encountered the issue.
> pod 'Crisp'

https://github.com/user-attachments/assets/7b3932a4-b894-47b2-95c1-c42c1618573d

**Comment by reygie25** [comment]
Our team investigated this issue, which will only occur on a paid plan. We tried downgrading the plan, and the Chat View UI works perfectly.

**Comment by eliottvincent** [comment]
Hey, can you let us know what iOS SDK version you use?

**Comment by reygie25** [comment]
I didn't specify an SDK version in the pod file, so I think I'm using the latest version
![image](https://github.com/user-attachments/assets/816b861f-8697-46a8-bc0f-19413c41686f)

**Comment by nesium** [comment]
Hi @reygie25. Thanks for your report. The issue should be fixed in [2.5.5](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.5.5). Please let us know if that works for you.
