### ISSUE TITLE
[SwiftUI] Conversations don't appear when typing message

### ISSUE THREAD

**Issue by Franciscortega** [crisp-im/crisp-sdk-ios#99]
Hi ! 

I'm using the iOS SDK to present the ChatViewController() through UIViewControllerRepresentable in SwiftUI : 

```
import Foundation
import CrispWebRTC

import SwiftUI
struct CrispViewRepresentable: UIViewControllerRepresentable {
    typealias UIViewControllerType = ChatViewController
    
    func makeUIViewController(context: Context) -> ChatViewController {
        ChatViewController()
    }
    
    func updateUIViewController(_ uiViewController: ChatViewController, context: Context) {
        // Updates the state of the specified view controller with new information from SwiftUI.
    }
}
```

I then present it in a sheet  : 
```
 .sheet(isPresented: $openCripsSheet, content: {
                CrispViewRepresentable()
            })
```

The sheet appears correctly, but when starting to type a message, the messages go up and become invisible, including the currently redacted message and the send button  : 
![IMG_ED251B2A8A52-1](https://github.com/user-attachments/assets/7975bdb3-f006-4d11-8cfa-2a21ea3067ee)

**Comment by nesium** [comment]
Hi @Franciscortega. Please use the [`ChatView`](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/chatview) instead of wrapping the `ChatViewController`. That should solve your problem.
